### ISSUE TITLE
Support for the Re-created Spectrum bluetooth keyboard

### ISSUE THREAD

**Issue by mitchelln** [MiSTer-devel/ZX81_MiSTer#5]
Feature request if I may. It would be great if the Re-created Spectrum bluetooth keyboard could be supported. At least 90% of the keys match, certainly all the major ones you need. It's the closet we'll ever get to having an external ZX81 bluetooth keyboard.
Thanks!

**Comment by sorgelig** [comment]
This is worth when this core will be the only one used on the board. Something like replica of ZX81.
What will you do with such keyboard on ao486 or Minimig cores?

**Comment by mitchelln** [comment]
It would only get used for the Sinclair cores. 
The keyboard is currently already supported by the Spectrum cores and is really useful, as it has all the custom keys. It would be a similarly useful addition for the ZX81 core.
I would not expect a generic driver for use with other cores.

**Comment by sorgelig** [comment]
Spectrum keyboard is similar to ZX81. So i will see if i can do it for ZX81. I have no such keyboard and it will be hard to test it for me.

**Comment by mitchelln** [comment]
That is very generous of you. Thank you. I can help test it.

**Comment by sorgelig** [comment]
i've added changes, so you can try in upcoming unstable build

**Comment by mitchelln** [comment]
Wow, that was quick! Yes, sure I will test it. 
Thank you.

**Comment by mitchelln** [comment]
I've just tested this and it works perfectly. Really transforms the usability of the core! 
Thank you for implementing this.
